name: 첫번째 GitHub Action
on:
    push:
        branches:
            - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: 01-th Step
        run: echo "Hello World"

      - name: 02-th Step
        run: echo "GitHub World"    
